spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ad_dev
    username: ad_dev_user
    password: dxy
    platform: mysql #used for load data-{platform}.sql

    # set this initialization-mode property to always so that data-h2.sql get executed, the default value is 'embedded', which means
    # when use mysql, the data-h2.sql will not be executed.
    # of course, it's be commented because it's only for the first time.

    #    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

    # add the following part and run the project, a sql file named 'guru_database_create.sql' can be generated
    # and the root directory of the project. The content in that file can then be used to generate tables in the mysql database.
    # do note that there is no semicolon an the end of each line in that file, so make sure add them before run them.

#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql
